Try updating deps
Builds are currently failing with:

```
10:41:50 AM: ERROR in /opt/build/repo/src/components/GameBoard.spec.tsx
10:41:50 AM: ERROR in /opt/build/repo/src/components/GameBoard.spec.tsx(8,23):
10:41:50 AM: TS2307: Cannot find module './GameBoard'.
10:41:50 AM: ERROR in /opt/build/repo/src/scenes/GamePage.tsx
10:41:50 AM: ERROR in /opt/build/repo/src/scenes/GamePage.tsx(9,23):
10:41:50 AM: TS2307: Cannot find module '../components/GameBoard'.
10:41:50 AM: Child html-webpack-plugin for "index.html":
10:41:50 AM:      1 asset
10:41:50 AM:     Entrypoint undefined = index.html
10:41:50 AM:     [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 470 bytes {0} [built]
10:41:50 AM:     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
10:41:50 AM:     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
10:41:50 AM:         + 1 hidden module
```

This is really odd because it's only happening when building in
Netlify.